openapi: "3.0.0"
info:
  version: 1.0.0
  title: "App"
  description: "Esta é uma api de Teste"
  license:
    name: MIT
  contact:
    name: J.S.Júnior
    email: j.s.junior@live.com
servers:
  - url: "https://app.local/"
    description: "Api de Dev"
tags:
  - name: auth
    description: "Responsável por `criar usuário`, `logar usuário`"
  - name: transactions
    description: "Responsável por `efetuar uma transferencia`"

paths:
  /auth/login:
      post:
        tags:
          - auth
        summary: Autentica o usuário
        description: 'Autentica o usuário'
        requestBody:
          content:
            'application/json':
              schema:
                type: object
                properties:
                  email:
                    type: string
                  password:
                    type: string
        responses:
          '200':
            description: successful operation
          '401':
            description: Unauthorized
          '400':
            description: Bad request
  /auth/signin:
    post:
      tags:
        - auth
      summary: Cadastra um usuário
      description: 'Cadastra um usuário'
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                profile:
                  type: string
                  example: "user|retailer"
                email:
                  type: string
                document:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string

      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
  /transactions/transfer:
    post:
      tags:
        - transactions
      summary: Efetua uma transferncia
      description: 'Efetua uma transferncia'
      requestBody:
        content:
          'application/json':
            schema:
              type: object
              properties:
                document:
                  type: string
                value:
                  type: number
      responses:
        '200':
          description: successful operation
        '400':
          description: Bad request
